# Generated by Django 5.0.3 on 2024-06-17 16:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Complain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("reportername", models.CharField(max_length=100)),
                ("reporterphone", models.CharField(max_length=20)),
                ("reporteremail", models.EmailField(max_length=254)),
                ("attachment", models.TextField()),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "complain",
            },
        ),
        migrations.CreateModel(
            name="Dustbin",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("percentage", models.CharField(max_length=5)),
                ("status", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "dustbin",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("description", models.TextField()),
                ("attachment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "report",
            },
        ),
    ]
